### ISSUE TITLE
admin/admin combo not working out of the box

### ISSUE THREAD

**Issue by ozeta** [marcopompili/docker-nginx-git#1]
steps to reproduce:

docker run -d -p 8180:80 -v /git:/srv/git emarcs/nginx-git
git clone http://localhost:8180/myrepo.git

error:

Cloning into 'myrepo'...
Username for 'http://localhost:8180': admin
Password for 'http://admin@localhost:8180':
fatal: unable to access 'http://localhost:8180/myrepo.git/': The requested URL returned error: 403

**Comment by auguster** [comment]
That's because the htpasswd is not included in the dockerfile, you have to mount your own htpasswd into /srv/htpasswd.
